---
- name: Get the list of installable packages
  set_fact:
    _postfix_packages: >-
      {%- if postfix_packages is not none -%}
      {{ postfix_packages }}
      {%- elif (
        (ansible_distribution|lower in __postfix_packages)
        and (ansible_distribution_major_version|int in __postfix_packages[ansible_distribution|lower])
      ) -%}
      {{ __postfix_packages[ansible_distribution|lower][ansible_distribution_major_version|int] }}
      {%- elif (
        (ansible_distribution|lower in __postfix_packages)
        and ('default' in __postfix_packages[ansible_distribution|lower])
      ) -%}
      {{ __postfix_packages[ansible_distribution|lower]['default'] }}
      {%- else -%}
      []
      {%- endif -%}
