---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos-7-postfix
    image: centos:centos7
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /usr/sbin/init
  - name: centos-8-postfix
    image: rockylinux:8
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /usr/sbin/init
provisioner:
  name: ansible
verifier:
  name: ansible
